### ISSUE TITLE
Some love for tests

### ISSUE THREAD

**Issue by augi** [avast/rabbitmq-scala-client#11]
I have to restart builds in Travis several times because of some random issues. It's hard to know what's going wrong because even passing tests generate a lot of error messages. Additionally, it's not possible to run tests in IDEA.

1. Make the tests easily executable in IDEA.
2. Clean up output from tests.
3. Stabilize the tests (e.g. increase timeouts).

**Comment by jendakol** [comment]
Should be done in v9.
