### ISSUE TITLE
No error message and no messages in Rabbit

### ISSUE THREAD

**Issue by favalos** [avast/rabbitmq-scala-client#28]
Hi,

I found your library very interesting, and I am trying it. But I cannot get it working. It is compiling successfully but I can not get an error message and I can not see any connection to my RabbitMQ docker. I am trying to write a producer for one of my microservices.

The I call this service is: 

MQService("Send Test Message.")

This is my code, please let me know if I am not using it correctly and what is the best practice to handle error messages:

import java.util.concurrent.{ExecutorService, Executors}

import cats.effect.{Resource}
import com.avast.bytes.Bytes
import com.avast.clients.rabbitmq._
import com.avast.clients.rabbitmq.api.RabbitMQProducer
import com.avast.metrics.scalaapi.Monitor
import com.typesafe.config.ConfigFactory
import monix.eval._
import monix.execution.Scheduler

import scala.concurrent.ExecutionContext

class MQService {

  val config = ConfigFactory.load().getConfig("myConfig")

  val blockingExecutor: ExecutorService = ExecutionContext.fromExecutorService(Executors.newCachedThreadPool())
  implicit val sch: Scheduler = Scheduler(Executors.newCachedThreadPool())

  val monitor: Monitor = Monitor.noOp()

  val rabbitMQProducer: Resource[Task, RabbitMQProducer[Task, Bytes]] = {
    for {
      connection <- RabbitMQConnection.fromConfig[Task](config, blockingExecutor)

      producer <- connection.newProducer[Bytes]("producer", monitor)
    } yield {
      producer
    }
  }

}

object MQService {

  val service = new MQService()

  def apply(message: String) = {
    service.rabbitMQProducer.use { producer =>
      producer.send("1", Bytes.copyFrom(message.getBytes), None)
    }
  }
}
 
Thanks in advance,

**Comment by jendakol** [comment]
Hi @favalos,
thank you for the interest!
I believe when you check what the return type of your `MQService.apply` method is, you'll discover that it returns `Task[Unit]`. The problem is that you never run the `Task`, based on what I see in the code :smiley: Rest of the code looks good, try to run the `Task` and let me know :-)

**Comment by favalos** [comment]
Hey Jendakol,
That was fast!
You are totally right. It is working now.
This change did the trick...

Thank you so much,

object MQService {

  implicit val sch: Scheduler = Scheduler(Executors.newCachedThreadPool())

  val service = new MQService()

  def apply(message: String) = {
    service.rabbitMQProducer.use { producer =>
      producer.send("1", Bytes.copyFrom(message.getBytes), None)
    }.runAsync( resp => resp match {
      case Left(e) => e.printStackTrace()
      case _ =>
    })
  }
}

**Comment by jendakol** [comment]
I'm glad I could help ;-)

P.S. If I may have an advice for you, you may want to check https://guides.github.com/features/mastering-markdown/, your posts would be more readable with proper formatting :wink:
