### ISSUE TITLE
Microservice implementation with Cats IOApp

### ISSUE THREAD

**Issue by favalos** [avast/rabbitmq-scala-client#29]
Hi,

Do you have any example on how to implement a micro service with the library and Cats IOApp?

Our idea is to launch the micro service using Cats IOApp, when something is pushed to the Queue the consumer will be the entry point for the service, we will be able to do some work with the inbound and write the output back to a different Exchange.

Thanks,

**Comment by jendakol** [comment]
Hi,
no offense, but I don't have enough time to provide advices to all people on the internet :-) And TBH, this is almost not related to the client (which I'm glad you use). For this time, I'm gonna make an exception and provide pseudo-code to you, but this really doesn't belong to *issues* of RMQ client.
1. Create connection
1. Create producer from the connection
1. Create your service with the producer as dependency, doing your stuff and publishing some message afterwards
1. Create consumer from the connection, with the service as a handler
1. Now you should have a `Resource` of the whole program, just call `use` and glue it into the `IOApp`.

Consider using official docs for [IOApp](https://typelevel.org/cats-effect/datatypes/ioapp.html) and [Resource](https://typelevel.org/cats-effect/datatypes/resource.html).
