### ISSUE TITLE
Scala 2.13 cross-build

### ISSUE THREAD

**Issue by lukoyanov** [avast/rabbitmq-scala-client#41]
Hi.

Thank you for creating and supporting this client.
Do you plan to release a version for scala 2.13?

**Comment by lukoyanov** [comment]
@jendakol would you please give me a hint when 2.13 is going to be supported?

**Comment by jendakol** [comment]
Oh yay, I totally forgot about this issue! 2.13 is supported from yesterday :smile: Check out [8.0.0 release](https://github.com/avast/rabbitmq-scala-client/releases/tag/8.0.0) :wink:
