### ISSUE TITLE
Version 8.0.1 does not resolve.

### ISSUE THREAD

**Issue by sdgomez** [avast/rabbitmq-scala-client#51]
Hi guys, 
I want to use your library, but when I imported the latest version of the library I got this error, help me, please :)
![no resuelve](https://user-images.githubusercontent.com/19391781/88460012-d1c7c780-ce5e-11ea-918b-1bb0c6b99ed6.png)

**Comment by sdgomez** [comment]
I solved the problem adding this to the build.sbt:

resolvers += "maven r2" at "https://dl.bintray.com/avast/maven/"

**Comment by jendakol** [comment]
Hello @sdgomez, this library is published to JCenter only. You should not need Avast-specific repo to be added (even though it works), using generic `Resolver.jcenterRepo` should work too. Let me know if that helped. Thx.
