### ISSUE TITLE
Example project

### ISSUE THREAD

**Issue by piotrkosecki** [avast/rabbitmq-scala-client#54]
I'm trying to evaluate your library to possibly use it in the project. I would be really helpful if you could provide minimal working project example(example from the readme does not work for me - probably my fault, but investigating why would be much easier when I could compare to actual working one).

**Comment by jendakol** [comment]
@piotrkosecki OK, I could try :thinking: Which kind of functionality are you interested in?

**Comment by piotrkosecki** [comment]
My case is basic producing/consuming messages with protobuf serialization(but I guess any serialization would do) with two separate services and a docker-compose file with the rabbitmq container and it's settings.

**Comment by jendakol** [comment]
Did you check [LiveTest](https://github.com/avast/rabbitmq-scala-client/blob/master/core/src/test/scala/com/avast/clients/rabbitmq/LiveTest.scala)?
