### ISSUE TITLE
Customize the rabbitMQ connection factory

### ISSUE THREAD

**Issue by tzimisce012** [avast/rabbitmq-scala-client#57]
Is there any way to customize the connection factory created on RabbitMQConnection class? Any suggestion on how to do this? If this is not possible, are PRs welcome? 

In my particular case, I would like to modify the max of channels allowed

**Comment by jendakol** [comment]
Hello @tzimisce012, no such limitation is currently available. We never really had such need but I wouldn't mind if you want to submit a PR.

However, you can e.g. create a wrapping connection or even add a new factory method to the `RabbitMQConnection` via an extension method - see what is done in the [`pureconfig`](https://github.com/avast/rabbitmq-scala-client/blob/master/pureconfig/src/main/scala/com/avast/clients/rabbitmq/pureconfig/pureconfig.scala#L20) module.

**Comment by jendakol** [comment]
Will be solved in v9.
