### ISSUE TITLE
Maven Central publishing

### ISSUE THREAD

**Issue by augi** [avast/rabbitmq-scala-client#69]
As [JCenter will shut down on May 1st, 2021](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), we have to start publishing to Maven Central.

**Comment by jendakol** [comment]
It's in progress. However, not that easy to do...

**Comment by augi** [comment]
Cool! 👍  Can understand.

**Comment by sideeffffect** [comment]
If you make the decision to move over to sbt (it has easy publishing to Maven), I can help :+1: (But maybe it's easy to do with Gradle as well, I don't really know.)

**Comment by augi** [comment]
How is it going, @jendakol ? I've successfully published a Scala project managed in Gradle to the Maven Central, so it could be easy for me.

**Comment by jendakol** [comment]
@augi  Oh did you? TBH I'm a little bit stuck, postponing this as I don't know how to continue :smile: If you think your method will work for this too, I'd appreciate you doing it.
